# APPNICENAME=Stash
# APPDESCRIPTION=An organizer for your porn, written in Go
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8080
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash
      ## The left part is the path on your host, the right part is the path in the stash container.

      ## Keep configs, scrapers, and plugins here.
      - ./config:/root/.stash
      ## Point this at your collection.
      ## The left side is where your collection is on your host, the right side is where it will be in stash.
      - ${ROOT_FOLDER_HOST}/media/data/videos/stash:/data
      ## This is where your stash's metadata lives
      - ${APP_DATA_DIR}/data/metadata:/metadata
      ## Any other cache content.
      - ${APP_DATA_DIR}/data/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - ${APP_DATA_DIR}/data/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - ${ROOT_FOLDER_HOST}/media/data/videos/stash/generated:/generated
